# Generated by Django 5.2.11 on 2026-03-01 03:18
# Data migration: add missing stations, fix line associations post-Regional Connector

from django.db import migrations


def update_stations(apps, schema_editor):
    Station = apps.get_model('ratemetroapp', 'Station')
    MetroLine = apps.get_model('ratemetroapp', 'MetroLine')

    # ── Helper: get or create a station, return (station, created) ──
    def get_or_create_station(name, lat, lng):
        try:
            s = Station.objects.get(name=name)
            return s, False
        except Station.DoesNotExist:
            s = Station.objects.create(name=name, latitude=lat, longitude=lng)
            return s, True

    # ── Ensure all line codes exist ──
    line_data = {
        'A': ('A Line (Blue)', '#0072bc', '#fff'),
        'B': ('B Line (Red)', '#e3242b', '#fff'),
        'C': ('C Line (Green)', '#58a738', '#fff'),
        'D': ('D Line (Purple)', '#a05da5', '#fff'),
        'E': ('E Line (Expo)', '#fdb913', '#000'),
        'G': ('G Line (Orange)', '#f58220', '#000'),
        'K': ('K Line (Crenshaw)', '#d11242', '#fff'),
    }
    lines = {}
    for code, (name, color, text_color) in line_data.items():
        try:
            line = MetroLine.objects.get(code=code)
        except MetroLine.DoesNotExist:
            line = MetroLine.objects.create(code=code, name=name, color=color, text_color=text_color)
        lines[code] = line

    # ── Remove the old L Line — reassign its stations to A Line ──
    try:
        l_line = MetroLine.objects.get(code='L')
        # Get all stations currently on L Line
        l_stations = list(l_line.stations.all())
        for station in l_stations:
            station.lines.add(lines['A'])
            station.lines.remove(l_line)
        l_line.delete()
    except MetroLine.DoesNotExist:
        pass

    # ── Remove J Line (Silver) if it exists — it's a bus, not rail ──
    try:
        j_line = MetroLine.objects.get(code='J')
        j_line.delete()
    except MetroLine.DoesNotExist:
        pass

    # ── 1. Regional Connector stations (A + E Lines) ──
    regional_connector = [
        ('Grand Ave Arts/Bunker Hill', 34.0550, -118.2512),
        ('Historic Broadway', 34.0520, -118.2466),
        ('Little Tokyo/Arts District', 34.0488, -118.2388),
    ]
    for name, lat, lng in regional_connector:
        s, _ = get_or_create_station(name, lat, lng)
        s.lines.add(lines['A'], lines['E'])

    # ── 2. E Line — East LA extension (7 stations) ──
    east_la_stations = [
        ('Pico/Aliso', 34.0476, -118.2260),
        ('Mariachi Plaza/Boyle Heights', 34.0475, -118.2191),
        ('Soto', 34.0436, -118.2102),
        ('Indiana', 34.0343, -118.1922),
        ('Maravilla', 34.0331, -118.1680),
        ('East LA Civic Center', 34.0334, -118.1612),
        ('Atlantic', 34.0334, -118.1546),
    ]
    for name, lat, lng in east_la_stations:
        s, _ = get_or_create_station(name, lat, lng)
        s.lines.add(lines['E'])

    # ── 3. E Line — also add LATTC/Ortho Institute ──
    s, _ = get_or_create_station('LATTC/Ortho Institute', 34.0291, -118.2735)
    s.lines.add(lines['E'])

    # ── 4. A Line — Foothill Extension Phase 2B (opened Sep 2025) ──
    foothill_stations = [
        ('Glendora', 34.1322, -117.8667),
        ('San Dimas', 34.1052, -117.8060),
        ('La Verne/Fairplex', 34.0974, -117.7688),
        ('Pomona North', 34.0936, -117.7533),
    ]
    for name, lat, lng in foothill_stations:
        s, _ = get_or_create_station(name, lat, lng)
        s.lines.add(lines['A'])

    # ── 5. Ensure existing E Line stations have correct associations ──
    # Pico station is shared A + E
    try:
        pico = Station.objects.get(name='Pico')
        pico.lines.add(lines['A'], lines['E'])
    except Station.DoesNotExist:
        pass

    # 7th St/Metro Center is A + B + D + E
    try:
        seventh = Station.objects.get(name='7th St/Metro Center')
        seventh.lines.add(lines['A'], lines['B'], lines['D'], lines['E'])
    except Station.DoesNotExist:
        pass

    # Union Station is A + B + D (no longer L)
    try:
        union = Station.objects.get(name='Union Station')
        union.lines.add(lines['A'], lines['B'], lines['D'])
    except Station.DoesNotExist:
        pass

    # ── 6. K Line + C Line shared stations ──
    # These C Line stations also serve K Line
    shared_ck = ['Douglas', 'El Segundo', 'Mariposa']
    for name in shared_ck:
        try:
            s = Station.objects.get(name=name)
            s.lines.add(lines['K'])
        except Station.DoesNotExist:
            pass

    # LAX/Metro Transit Center (C + K)
    s, _ = get_or_create_station('LAX/Metro Transit Center', 33.9501, -118.3787)
    s.lines.add(lines['C'], lines['K'])

    # Aviation/Century (C + K)
    s, _ = get_or_create_station('Aviation/Century', 33.9481, -118.3793)
    s.lines.add(lines['C'], lines['K'])

    # Crenshaw station on C Line
    s, _ = get_or_create_station('Crenshaw', 33.9258, -118.3267)
    s.lines.add(lines['C'])


def reverse_update(apps, schema_editor):
    # Reverse is complex — just pass
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ratemetroapp', '0005_chatconversation_chatmessage_and_more'),
    ]

    operations = [
        migrations.RunPython(update_stations, reverse_update),
    ]
