# Generated by Django 5.2.11 on 2026-03-04 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemetroapp', '0006_update_metro_stations_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='station_images/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ratemetroapp.station')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
                'constraints': [models.UniqueConstraint(fields=('station', 'order'), name='unique_station_image_order')],
            },
        ),
    ]
